name: rice_application
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  device_preview: ^1.2.0
  touchable_opacity: ^1.2.0
  smooth_page_indicator: ^1.2.0+3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  pinput: ^5.0.0
  google_sign_in: ^6.2.1
  country_code_picker: ^3.0.0
  lottie: ^3.1.2
  quickalert: ^1.1.0
  image_picker: ^0.8.4+4
  cloud_firestore: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  firebase_database: ^11.0.4
  firebase_storage: ^12.1.3
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_stripe: ^11.1.0
  flutter_dotenv: ^5.0.2
  dio: ^5.7.0
  flutter_rating_bar: ^4.0.1
  weather: ^3.1.1
  geolocator: ^13.0.1
  geocoding: ^2.0.4
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_tflite: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Rice/
    - assets/Logos/
    - assets/images/Icons/
    - assets/Animations/
    - assets/new_rice_classifier_model.tflite
    - assets/labels.txt
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
    - family: Manrope
      fonts:
        - asset: fonts/Manrope.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans.ttf
    - family: PlusJakarta
      fonts:
        - asset: fonts/PlusJakarta.ttf
