// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ox_MZUXCq5O1Sotp4b1d56MqRj8HGo4',
    appId: '1:614910018724:web:e3314331fcc0e992ab9231',
    messagingSenderId: '614910018724',
    projectId: 'riceapp01',
    authDomain: 'riceapp01.firebaseapp.com',
    storageBucket: 'riceapp01.appspot.com',
    measurementId: 'G-KYYQ7Y29GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLryrGOOBIn9m8rGKSY5eRDmNastQV0W8',
    appId: '1:614910018724:android:5fecddbe87bd8549ab9231',
    messagingSenderId: '614910018724',
    projectId: 'riceapp01',
    storageBucket: 'riceapp01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Tojw1CP4iD7pt381-bqfFb6rynRl-sA',
    appId: '1:614910018724:ios:91c3b0d390b04e91ab9231',
    messagingSenderId: '614910018724',
    projectId: 'riceapp01',
    storageBucket: 'riceapp01.appspot.com',
    iosBundleId: 'com.example.riceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Tojw1CP4iD7pt381-bqfFb6rynRl-sA',
    appId: '1:614910018724:ios:91c3b0d390b04e91ab9231',
    messagingSenderId: '614910018724',
    projectId: 'riceapp01',
    storageBucket: 'riceapp01.appspot.com',
    iosBundleId: 'com.example.riceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ox_MZUXCq5O1Sotp4b1d56MqRj8HGo4',
    appId: '1:614910018724:web:40df3b3c920253c4ab9231',
    messagingSenderId: '614910018724',
    projectId: 'riceapp01',
    authDomain: 'riceapp01.firebaseapp.com',
    storageBucket: 'riceapp01.appspot.com',
    measurementId: 'G-51WQ6GMQP5',
  );
}
